### ISSUE TITLE
Time to send this plugin to an official repo ?

### ISSUE THREAD

**Issue by rickybiscus** [vlmaksime/script.module.simpleplugin#18]
Hi,

I'm very glad that this plugin has been updated for Kodi Matrix; thanks @vlmaksime !

Wouldn't it be nice to submit this plugin in an official repo ?

Actually, I need to include it (hardcoded) in my own plugin, or it would need people to [manually install it before my plugin](https://www.tvaddons.co/kodi-addons/show/script.module.simpleplugin3/); which is not very handy.

Would it be possible ?

**Comment by vlmaksime** [comment]
I've already done a PR with this plugin, but it hasn't been accepted yet.
https://github.com/xbmc/repo-scripts/pull/1970
https://github.com/xbmc/repo-scripts/pull/1971

**Comment by vlmaksime** [comment]
Now addon available at Krypton, Leia and Matrix repository.
