### ISSUE TITLE
Ownership Transfer 

### ISSUE THREAD

**Issue by romanvm** [vlmaksime/script.module.simpleplugin#19]
@vlmaksime Since you are developing this project now I'd like to transfer ownership of it to you if you don't mind.

**Comment by vlmaksime** [comment]
I'm not against. But I'm afraid that all your links to the plugin from third-party resources will stop working.

**Comment by romanvm** [comment]
I'm not sure if there are such links. In any case I'm going to start ownership transfer.

**Comment by romanvm** [comment]
To do the transfer you need to remove your own fork of this repo.

**Comment by vlmaksime** [comment]
I removed my fork.

**Comment by vlmaksime** [comment]
@romanvm The transfer link has expired. Please repeat the transfer.

**Comment by romanvm** [comment]
Done
